### ISSUE TITLE
Two left plots typo

### ISSUE THREAD

**Issue by locua** [mspeekenbrink/sdam-book#1]
https://github.com/mspeekenbrink/sdam-book/blob/44e05756fa54b87d43d452c6d135cb631d4b24a9/05-GLM-moderation.Rmd#L131

Should the sentence starting "In the plot on the left..." instead say the "In the plot on the right..."; the parallel (not moderated models) are on the left and the non-parallel (moderated models) are on the right.

**Comment by mspeekenbrink** [comment]
Thanks @locua You are absolutely right. This should be fixed now.
