### ISSUE TITLE
Minor Typos in Chapter 3

### ISSUE THREAD

**Issue by dilayercelik** [mspeekenbrink/sdam-book#2]
Hey, I'm going through this chapter right now and I spotted (very) minor typos / ambiguities.

1) There seems to be a missing verb or a problem with the parentheses in `One important reason we'll mention later (the Central Limit Theorem)`?
- https://github.com/mspeekenbrink/sdam-book/blob/2865cc86a796443ca0df7c56b886cd662c9c9088/03-GLM-simple.Rmd#L75

2) Just need to edit "a<s>n</s> specific"
- https://github.com/mspeekenbrink/sdam-book/blob/2865cc86a796443ca0df7c56b886cd662c9c9088/03-GLM-simple.Rmd#L185

3) I'm not sure about this but to me it seemed like the 2 lines below were repetitions (of lines 312-313)?
- https://github.com/mspeekenbrink/sdam-book/blob/2865cc86a796443ca0df7c56b886cd662c9c9088/03-GLM-simple.Rmd#L321-L322

4) Not sure again, but just to check, did you mean "[...] from which we can draw <s>of</s> *or* simulate values."?
- https://github.com/mspeekenbrink/sdam-book/blob/2865cc86a796443ca0df7c56b886cd662c9c9088/03-GLM-simple.Rmd#L366

**Comment by mspeekenbrink** [comment]
Thanks, that is really helpful! Feel free to log more issues; the book is evolving and your support is extremely valuable.

Best wishes
Maarten
