### ISSUE TITLE
Minor typos in Chap 7

### ISSUE THREAD

**Issue by dilayercelik** [mspeekenbrink/sdam-book#5]
"[...] then we have the <s>the</s> model we wanted for this condition."
- https://github.com/mspeekenbrink/sdam-book/blob/d0d85e1bdbc8e6fe1ea8faddcf2e927b6f5aa2d5/07-ANOVA.Rmd#L93

$ sign in the titles of Table 7.1 and Table 7.2: "Values under  $\\hat{\\beta}$**$** are parameter estimates."
- https://github.com/mspeekenbrink/sdam-book/blob/d0d85e1bdbc8e6fe1ea8faddcf2e927b6f5aa2d5/07-ANOVA.Rmd#L118
- https://github.com/mspeekenbrink/sdam-book/blob/d0d85e1bdbc8e6fe1ea8faddcf2e927b6f5aa2d5/07-ANOVA.Rmd#L335

"[...] but <s>its</s> _it's_ more interesting from a data analysis perspective."
- https://github.com/mspeekenbrink/sdam-book/blob/d0d85e1bdbc8e6fe1ea8faddcf2e927b6f5aa2d5/07-ANOVA.Rmd#L252

"[...] independent predictors and <s>and</s> a neat division of the whole model SSR [...]"
- https://github.com/mspeekenbrink/sdam-book/blob/d0d85e1bdbc8e6fe1ea8faddcf2e927b6f5aa2d5/07-ANOVA.Rmd#L551

**Comment by mspeekenbrink** [comment]
Thanks! This is super helpful! Should be fixed now.
